# Generated by Django 3.1.4 on 2020-12-24 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=254, verbose_name='Nombre')),
                ('fecha_hora', models.DateTimeField(unique=True, verbose_name='Fecha y Hora')),
                ('motivo', models.TextField(verbose_name='Persona o Motivo')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
